-- Legacy seed for `public.cases` (appendicitis JSON) removed.
-- The app uses Synthea `patients` / `conditions` / `observations` and `sessions.patient` → `patients."Id"`.
-- Import clinical CSVs via your pipeline or Supabase Table Editor.
